#!/usr/bin/env python3

"""
Compute abstract walls in a combinatorial 2-complex.

An abstract wall is an equivalence class of 1-cells under the relation
generated by declaring opposite edges of every 2-cell to be parallel.

Input:
    vertices : optional list of vertex labels
    edges    : dictionary
               edge_id -> (initial_vertex, terminal_vertex)
    polygons : list of polygons, where each polygon is a cyclically
               ordered list of edge IDs

Example:
    edges = {
        0: (0, 1),
        1: (1, 2),
        2: (2, 3),
        3: (3, 0),
    }

    polygons = [
        [0, 1, 2, 3]
    ]

The polygon declares:
    0 ~ 2
    1 ~ 3

so the abstract walls are:
    {0, 2}
    {1, 3}
"""


class UnionFind:
    """Disjoint-set / union-find data structure."""

    def __init__(self, elements):
        self.parent = {x: x for x in elements}
        self.rank = {x: 0 for x in elements}

    def find(self, x):
        """Return the representative of the equivalence class of x."""
        if self.parent[x] != x:
            self.parent[x] = self.find(self.parent[x])
        return self.parent[x]

    def union(self, x, y):
        """Declare x and y equivalent."""
        root_x = self.find(x)
        root_y = self.find(y)

        if root_x == root_y:
            return

        # Union by rank
        if self.rank[root_x] < self.rank[root_y]:
            self.parent[root_x] = root_y
        elif self.rank[root_x] > self.rank[root_y]:
            self.parent[root_y] = root_x
        else:
            self.parent[root_y] = root_x
            self.rank[root_x] += 1

    def classes(self):
        """Return the equivalence classes as a dictionary."""
        result = {}

        for x in self.parent:
            root = self.find(x)
            result.setdefault(root, []).append(x)

        return result


def compute_abstract_walls(edges, polygons, verbose=False):
    """
    Compute the abstract walls of a combinatorial 2-complex.

    Parameters
    ----------
    edges : dict
        Dictionary mapping edge IDs to their endpoints.

    polygons : list[list]
        Each polygon is a cyclically ordered list of edge IDs.

    verbose : bool
        If True, print every parallelism relation discovered.

    Returns
    -------
    walls : list[list]
        The abstract walls, represented as lists of edge IDs.
    """

    edge_ids = set(edges.keys())

    # Check that every polygon uses valid edges.
    for i, polygon in enumerate(polygons):
        for edge in polygon:
            if edge not in edge_ids:
                raise ValueError(
                    f"Polygon {i} contains edge {edge}, "
                    "which does not occur in the edge list."
                )

    # Every 2-cell must have an even number of sides.
    for i, polygon in enumerate(polygons):
        n = len(polygon)

        if n % 2 != 0:
            raise ValueError(
                f"Polygon {i} has {n} sides. "
                "Abstract walls require even-sided polygons."
            )

    uf = UnionFind(edge_ids)

    # Generate the parallelism relations.
    for polygon_number, polygon in enumerate(polygons):
        n = len(polygon)
        half = n // 2

        for i in range(half):
            e1 = polygon[i]
            e2 = polygon[i + half]

            if verbose:
                print(
                    f"Polygon {polygon_number}: "
                    f"edge {e1} || edge {e2}"
                )

            uf.union(e1, e2)

    # Extract the equivalence classes.
    walls = list(uf.classes().values())

    # Sort for predictable output.
    walls.sort(key=lambda W: min(W))

    for W in walls:
        W.sort()

    return walls


def print_walls(walls):
    """Pretty-print the abstract walls."""

    print(f"Number of abstract walls: {len(walls)}")
    print()

    for i, wall in enumerate(walls):
        print(f"Wall {i}: {wall}")


if __name__ == "__main__":

    # ------------------------------------------------------------
    # Example: one square
    # ------------------------------------------------------------

    edges = {
        0: (0, 1),
        1: (1, 2),
        2: (2, 3),
        3: (3, 0),
        4: (0,4),
        5: (4,5),
        6: (5,6),
        7: (6,7),
        8: (7,1)
    }

    polygons = [
        [0, 1, 2, 3], [0,4,5,6,7,8]
    ]

    walls = compute_abstract_walls(
        edges,
        polygons,
        verbose=True
    )

    print()
    print_walls(walls)